language: c
sudo: required
before_install:
  - sudo apt-get install gfortran

script:
  - gfortran -fprofile-arcs -ftest-coverage -O0 reader.f95 -o reader
  - g++ reader.cpp -o readerc
  - g++ quad_guass.cpp -o quad_guass
  - ./reader
  - ./readerc
  - ./quad_gauss

after_success:
  - bash <(curl -s https://codecov.io/bash)
